### ISSUE TITLE
Initial Release Notifier

### ISSUE THREAD

**Issue by Airblader** [Airblader/unclutter-xfixes#1]
Follow this issue (watch it or comment on it) to get notified once a first version is out.

**Comment by krompus** [comment]
A baby jellyfish is watching you!

**Comment by Airblader** [comment]
It should work now. However, the timeout is hardcoded to 1s. That will of course change. I'll also provide instructions for compiling and installing etc. I'll keep you up to date here.

**Comment by Airblader** [comment]
OK, everything should be up and running now. Of course more features can be added and there might be bugs etc., but those will be handled in their own issues now.
