### ISSUE TITLE
Compatible command syntax with original unclutter

### ISSUE THREAD

**Issue by ticalc-travis** [Airblader/unclutter-xfixes#14]
Given that unclutter-xfixes seems to aim at replacing the original unclutter (even using the same executable name), I think it would be good idea to have it accept as many of the original unclutter's command option names as possible to help make drop-in replacement go more smoothly. For instance, the option ‘-idle’ becomes ‘-timeout’ in unclutter-xfixes, requiring users to edit scripts/remember to use the new syntax/etc.. when migrating; it would be nice if unclutter-xfixes simply accepted the option ‘-idle’ as an alias for ‘-timeout’. Options which no longer apply like ‘-grab’, ‘-noevents’, etc., could perhaps be accepted but ignored for compatibility.

**Comment by Airblader** [comment]
I didn't actually intend unclutter-xfixes to be a drop-in replacement since I think it's easy enough to adapt the call. But I think your suggestion makes sense and I'd merge such a change. PRs welcome.

**Comment by Airblader** [comment]
P.S.: Sorry for the delay in answering, I've been on vacation.

**Comment by Airblader** [comment]
Here's a list of options of the original unclutter:

* `-display` → currently not implemented, but could be done.
* `-idle` → should be mapped to our timeout
* `-keystroke` → should be ignored
* `-jitter` → already implemented, but syntax isn't compatible.
* `-grab` → should be ignored
* `-noevents` → should be ignored
* `-reset` → should be ignored
* `-root` → already implemented, but syntax isn't compatible
* `-onescreen` → should be ignored
* `-not` → should be ignored, but a potential feature for the future.
