### ISSUE TITLE
Switch mouse off when inactive.

### ISSUE THREAD

**Issue by amosbird** [Airblader/unclutter-xfixes#16]
There are situations the UI responds to the current cursor's position, such as viewing code on github and browsing in Intellij with ideavim when pressing `Ctrl-d/u`. Can we just temporarily switch off mouse or move it to some alien space that it never bothers current UI?

**Comment by Airblader** [comment]
Sorry, switching the mouse off just isn't possible. Moving the mouse away might work on some systems, but will badly break things on focus follows mouse systems. This is exactly the kind of hacks to hide a mouse that the original unclutter uses, so not something for this project. You might just want to use the original unclutter and hole that it works for you. :)

**Comment by amosbird** [comment]
@Airblader I tried the original one. It doesn't work either. Anyway, thanks for the detailed explanation :)

**Comment by Airblader** [comment]
I'm not too familiar with the original, but I think you'd need to use the noevents flag for the behavior you're looking for.

**Comment by amosbird** [comment]
ah, great. Thanks.
