### ISSUE TITLE
Gentoo/Funtoo ebuild

### ISSUE THREAD

**Issue by michaelmrose** [Airblader/unclutter-xfixes#17]
Here is an example

https://gist.github.com/michaelmrose/f93125326cfa0b3ba85d4ea406324bb3

I had a question though the original declared that it depended on x11-libs/libX11 and 

x11-proto/xproto Description:   X.Org xproto protocol headers 

Should anything else be included, removed? Any other suggestions?

**Comment by Airblader** [comment]
Yeah, there are some dependencies. Take a look at the dependencies in the Arch package:  https://aur.archlinux.org/packages/unclutter-xfixes-git/

**Comment by Airblader** [comment]
Please also fix my name in that file. It's Airblader, not airbladder. :)

**Comment by michaelmrose** [comment]
np

**Comment by michaelmrose** [comment]
Ok so updated the gist to reflect the correct name and make the deps somewhat match what was given in the arch package. So a few questions

I didn't include git as I'm not getting it with git.  I'm supposing that  I can just ommit asciidoc as well?

Do you see any other problems?

**Comment by michaelmrose** [comment]
Also supposing xproto is no long needed

**Comment by Airblader** [comment]
Yeah, omitting git is fine. But building out of tree will result in the binary reporting an unknown version (unless you manually provide the version to make). 

You can't omit asciidoc, though, since you are still building the man pages.

**Comment by michaelmrose** [comment]
The ebuild is now part of funtoo

**Comment by Airblader** [comment]
Great, thanks! I can close this issue then, right? :-)

**Comment by michaelmrose** [comment]
It would be great if this could be mentioned in the readme

**Comment by Airblader** [comment]
Sure thing. Can you send a PR?

**Comment by michaelmrose** [comment]
I'm going to submit the ebuild to gentoo as well then submit pr to indicate it is available

**Comment by Airblader** [comment]
Sounds great, thanks!
