### ISSUE TITLE
Dependencies to build from source are undocumented

### ISSUE THREAD

**Issue by dvejmz** [Airblader/unclutter-xfixes#19]
The header files required to build `unclutter-xfixes` from source are not listed anywhere. I just uninstalled `unclutter` with my package manager and then tried to `make` unclutter-xfixes but I encountered a bunch of missing header file errors. Here are all the missing header files as well as the packages that you'd have to install on a Fedora system:

* `ev.h` -> `libev-devel`
* `Xlib.h` -> `libX11-devel`
* `XInput2.h` -> `libXi-devel`

These were the ones that I had to install in order to install successfully. In a Debian/Ubuntu box just remove all the `-devel`s and you should be good, I guess.

**Comment by Airblader** [comment]
Thanks, I'll add a DEPENDENCIES file. I won't add the package names, though, since they are distribution specific. Libraries like xcb-util-xrm should be installed from package, not source, and package maintainers should be able to figure out the correct package.

**Comment by mailinglists35** [comment]
can you add a reference to the dependecies file in the main readme.md? I naively followed the manual compilation that failed, then found this issue to find the answer...

**Comment by mailinglists35** [comment]
also dependencies contents is not that explicit as first comment which tells clear for a popular distribution what exactly is needed...

**Comment by Airblader** [comment]
Can you send a PR that adds the reference to the Readme?

As for distro specific names I won't do that as explained above. You shouldn't have a reason to install from source — the preferred way is a package. If one doesn't exist, either create one so everyone can profit from it or ask your distro maintainers to do so.

**Comment by Hund** [comment]
> can you add a reference to the dependecies file in the main readme.md? I naively followed the manual compilation that failed, then found this issue to find the answer...

The same thing just happened to me as well.
