### ISSUE TITLE
trying to compile in raspberry pi 3

### ISSUE THREAD

**Issue by 0raid** [Airblader/unclutter-xfixes#24]
Hello my friend , i have trying to compile in raspberry pi , the compilation was successfuly , but unclutter dont regonize the option --ignore-scrolling

any thoughs?

thanks!

**Comment by Airblader** [comment]
> any thoughs?

Yes – you need to provide a lot more information. What exactly you are doing, what exactly you are seeing. Closing until this information is available because right now this issue contains too few details to do anything with it.

**Comment by 0raid** [comment]
i am trying to setup a raspberry pi as information kiosk with touch monitor , i have put in the unclutter -idle 0 , so its hide the cursor so far no problem , but when you trying to scroll the screen with your finger the mouse cursor is visible.

**Comment by Airblader** [comment]
> but when you trying to scroll the screen with your finger the mouse cursor is visible.

But you said it doesn't recognize the option. What does that mean? Just that the behavior isn't working? Or do you actually get an error when running the command that the option isn't recognized?

>  have put in the unclutter -idle 0 , so its hide the cursor so far no problem

That's odd, seeing how `-idle` doesn't exist in unclutter-xfixes. Perhaps you actually installed the original unclutter and not unclutter-xfixes.

**Comment by 0raid** [comment]
ok let me be more clear , i have the original unclutter installed in my raspberry , running with the flag -idle 0 , the mouse cursor is invisibe , but when you scrolling the mouse is there again , so i have uninstall completed the original unclutter , and i have compile your version , after the compile i am trying to run the unclutter with "unclutter --ignore-scrolling" , but its not running its just tell me which flags is accepted (help option) and --ignore-scrolling is not there.

**Comment by Airblader** [comment]
So how did you compile unclutter-xfixes and what does `unclutter --version` say?
