### ISSUE TITLE
hide-on-touch not working

### ISSUE THREAD

**Issue by estekadigital** [Airblader/unclutter-xfixes#55]
If I am right, that option should hide the cursor when touching the screen, right? But this is not working in my system.

In openbox autostart I have the following:

`@unclutter -timeout 0.01 --hide-on-touch`

**Comment by Airblader** [comment]
What does "not work" mean? It starts but nothing happens? Or does the command fail? What version are you using?

**Comment by estekadigital** [comment]
It works, (hides the cursor on idle but not when touching the screen. The expected behaviour is that when I move the mouse it idles for 0.01 seconds, but when touching the screen it hides inmediately.. is this correct?

unclutter-xfixes version 1.6

**Comment by Airblader** [comment]
So you built this from source? Did you do so recently enough that the feature is already included (i.e., do you see it in `unclutter -h`)?

CC @nowrep

**Comment by estekadigital** [comment]
Yes I do:

`Usage: unclutter [--timeout <n>] [--jitter <radius>] [--exclude-root] [--ignore-scrolling] [--ignore-buttons <buttons>] [--hide-on-touch] [-b|--fork] [-v|--version] [-h|--help]`

**Comment by estekadigital** [comment]
@Airblader, any clue ?

**Comment by Airblader** [comment]
No, I was hoping @nowrep would join in since they PRed this initially. Something you could try is add some debug output in src/event.c to see which events are coming and why what should happen doesn't happen. Since you built from source perhaps you can do that? :-)

I will likely not release 1.6 if this issue stays open and if need be fall back to reverting it if necessary.

**Comment by thekuom** [comment]
For me, I ran into this issue because my touch screen was sending events as mouse button events, so I had to use the `--ignore-buttons` argument instead of `--hide-on-touch`

**Comment by bolbishvili** [comment]
> I will likely not release 1.6 if this issue stays open and if need be fall back to reverting it if necessary.

I just built this recently and it's working well with sxmo-ui on both pinephone and pinetab. We are interested in trying to include this in sxmo: https://todo.sr.ht/~mil/sxmo-tickets/28 if there's a newer release which includes this option.

**Comment by Airblader** [comment]
Thanks @bolbishvili! Given that OP never looked more into this and also the feedback by you and @thekuom, I think that should be fine. I will create a release shortly.

**Comment by Airblader** [comment]
Done: https://github.com/Airblader/unclutter-xfixes/releases/tag/v1.6

I'll also close this issue as not reproducible and stale.
