### ISSUE TITLE
--timeout option not respected (i3wm)

### ISSUE THREAD

**Issue by ivan94fi** [Airblader/unclutter-xfixes#56]
## Version
```bash
$ unclutter --version
unclutter-xfixes version 1.6
```
```bash
$ which unclutter
/usr/bin/unclutter
```
Installed with `git clone` + manual installation.
## System
Distribution: Ubuntu 18.04
Window manager: i3wm (version 4.17.1)

## Problem
In my i3wm config file I have this line
```bash
exec --no-startup-id /usr/bin/unclutter --ignore-scrolling --timeout 5
```
to execute unclutter at system start.

Unclutter is indeed executed but the `timeout` is 1 second long instead of the 5 seconds specified.

By executing `htop` and filtering by `unclutter` keyword, I get the following:
```
 PID   ...    TIME+   Command
2535   ---   0:00.00 ├─ /bin/sh -c /usr/bin/unclutter --ignore-scrolling --timeout 5
2538   ---   0:05.13 │  └─ /usr/bin/unclutter --ignore-scrolling --timeout 5
2514   ---   0:05.98 │  │  │  │  └+ /usr/bin/unclutter -idle 1 -root
```

So it seems that somehow a second unclutter instance is executed, with timeout set to 1 second.

If i kill the second instance, `kill 2514` in this case, i get the actual 5 seconds as specified.

I am aware this is likely due to something else than unclutter itself, but at the moment I cannot identify the source of the problem.

**Comment by Airblader** [comment]
Indeed I doubt this is an unclutter-xfixes issue :-) If you comment our your line, does one instance still launch? If so, something else must be launching the process.

**Comment by ivan94fi** [comment]
I will check this as soon as I can (I must logout from my session). The weird thing is that, according to htop, the `-idle 1` instance is spawned by the `--timeout 5` instance.

**Comment by ivan94fi** [comment]
As espected, the problem was **not** caused by unclutter-xfixes, but from a previous installation of the "original" unclutter — which I previously installed from Ubuntu repositories via `sudo apt install unclutter`, then uninstalled with `sudo apt remove unclutter` before adopting unclutter-xfixes. I will expose my solution hoping that someone can benefit from it.

Thank you @Airblader for the feedback and from the amazing tool.

### Problem
Unclutter installs the file `/etc/X11/Xsession.d/90unclutter` which executes `/usr/bin/unclutter` at X startup, with the default options provided in `/etc/default/unclutter`.

These files were not deleted when I uninstalled unclutter, so after installing unclutter-xfixes, they happened to start another "hidden" unclutter instance.

### Solution
The solution was:
* uninstalling unclutter-xfixes: `cd <unclutter-xfixes root>; sudo make uninstall`
* executing `sudo apt purge unclutter` to remove old config files from "original" unclutter
* finally reinstalling unclutter-xfixes with `sudo make install`
