### ISSUE TITLE
errx format not a string literal and no format arguments UBUNTU

### ISSUE THREAD

**Issue by BrendanBall** [Airblader/unclutter-xfixes#6]
I'm trying to compile this project but haven't had any luck so far. I've managed to install all the dependencies but coming up with an error now.

Distribution: Ubuntu 15.10 (64bit)
gcc version: gcc (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010
compile error: `src/util.c: In function ‘bail’:
src/util.c:6:5: warning: format not a string literal and no format arguments [-Wformat-security]
     errx(EXIT_FAILURE, message);`

full output:
`rm -f unclutter obj/extensions.o obj/unclutter.o obj/cursor.o obj/event.o obj/util.o
rm -f man/*.1 man/*.xml

gcc -D'__VERSION="heads/master-0-g17a95a8"' -Iinclude -std=gnu99 -Wall -Wundef -Wshadow -o obj/extensions.o -c src/extensions.c
gcc -D'__VERSION="heads/master-0-g17a95a8"' -Iinclude -std=gnu99 -Wall -Wundef -Wshadow -o obj/unclutter.o -c src/unclutter.c
gcc -D'__VERSION="heads/master-0-g17a95a8"' -Iinclude -std=gnu99 -Wall -Wundef -Wshadow -o obj/cursor.o -c src/cursor.c
gcc -D'__VERSION="heads/master-0-g17a95a8"' -Iinclude -std=gnu99 -Wall -Wundef -Wshadow -o obj/event.o -c src/event.c
gcc -D'__VERSION="heads/master-0-g17a95a8"' -Iinclude -std=gnu99 -Wall -Wundef -Wshadow -o obj/util.o -c src/util.c
src/util.c: In function ‘bail’:
src/util.c:6:5: warning: format not a string literal and no format arguments [-Wformat-security]
     errx(EXIT_FAILURE, message);
     ^
gcc -Iinclude -std=gnu99 -Wall -Wundef -Wshadow -o unclutter obj/extensions.o obj/unclutter.o obj/cursor.o obj/event.o obj/util.o -lX11 -lXi -lXfixes  -lev
a2x -f manpage man/unclutter-xfixes.man`

expected: compile safely without warnings

note: I'm not a C programmer, from what I've googled ubuntu gcc adds the flag `-Wformat-security` by default which brings up the warning. 
Is it possible to fix this without removing the flag?
I would really like to use this project as I'm having problems with i3 and intellij and hoping this project will fix it.

**Comment by Airblader** [comment]
I'm pretty sure I know how to fix it, this is just gcc being overly careful. It compiled just fine and will also work just fine, though.
