### ISSUE TITLE
Readme and manual page should be rewritten

### ISSUE THREAD

**Issue by rkmiec** [Airblader/unclutter-xfixes#61]
Current description of unclutter doesn't say what this application does but instead describes what it replaced.

I have put it once in my i3 startup script and forgot what was this about. Looking at the manual page was a dead-end.

**Comment by chelovechishko** [comment]
> Looking at the manual page was a dead-end

https://github.com/Airblader/unclutter-xfixes/blob/master/man/unclutter-xfixes.man#L92

**Comment by rkmiec** [comment]
Wow, it actually is there. Wouldn't it be easier to keep it on top of the manual page? I have never seen manual page written this way.

**Comment by Airblader** [comment]
Thanks for raising this. I absolutely agree that this should be on the very top and only then followed by a section explaining the history of it. If someone wants to send a PR that's much appreciated, otherwise I'll try to do it later today.
