### ISSUE TITLE
[Feature Suggestion] custom jitter for window match

### ISSUE THREAD

**Issue by Cardosaum** [Airblader/unclutter-xfixes#67]
First of all, I'd like to thank you all for this amazing program! 
I really enjoy it. 
:)

I was wondering if it would be possible to add a feature that permits to set a custom jitter to a specific set of windows rather than only setting jitter globally with the `--jitter` option

Something similar to what `--not` already does, but rather than hide the mouse totally, it would set a different jitter for that window.

For example, I'm glad with `--jitter=50` for most apps, but when reading pdfs and highlighting them I find this number a bit too big and end opting for something like `--jitter=1`. 
What I would like to have is an option like `--jitter-window=<jitter_value> <window_name` that enables me to more accurately fine tune the program.

It's just an idea, and I'd be happy to help (though I recognize I'm not already a great C programmer).

I was reading the source code but did'n find how to do it immediately...

Thanks in advance for your attention!

**Comment by Airblader** [comment]
The actual implementation here wouldn't be so bad, but in terms of API this is quite tricky as you need to define pairs of window match and jitter value, and, unfortunately, would likely have to refactor the entire arguments parsing (in a compatible way, no less). 

I'm not entirely convinced I want to extend unclutter-xfixes, a fairly simplare application, to this level of complexity. Perhaps running a local patch would be a significantly easier approach here? I'm happy to give pointers for that.

**Comment by Cardosaum** [comment]
I see...

No prob at all :)

I'll try to make some modifications. I think it will end up being a good opportunity to get a hands-on experience with C nonetheless haha

In case I get stuck in some implementation detail I think I'll reach you out, if it's not a problem.

Thanks for your attention!

**Comment by Airblader** [comment]
Thanks for understanding! I'll close this, but feel free to reach out.

**Comment by Cardosaum** [comment]
Well, it took some hours... But I think I made it! :D
[Here is the link for the code that I modified](https://github.com/Airblader/unclutter-xfixes/compare/master...Cardosaum:feature-window-jitter?expand=1)

I know that the code may lack quality , but I did my best haha

The argument parsing is one of the parts I know is not that great. I needed to
use a syntax like `<window>=<radius>`.

One other thing I noticed is that the CPU usage is quite high now. In my
computer it's twice as much:
 - Branch master: (1.3% ~ 2%) CPU usage.
 - Branch feture-window-jitter: (2% ~ 4%) CPU usage.

I think it's due to the overhead that linked lists cause to the lookup functions
(maybe I should change to use sequential arrays, as it's already used in the
`name_matches` function)

Anyway, I'm quite happy that now the feature is working :)

Would you mind to read the changes and point out some enhancements I could make
(or mistakes I made)?

That was the first time I poke around with a real project in C and I think that,
maybe, the quality could be significantly improved.

Please, don't feel pressure! Do it only if you really have time and are willing
to.

Thanks for your attention!

**Comment by Airblader** [comment]
Awesome! A couple things that stick out from a very quick look:

1. You're actually matching into your list twice for each event (`is_on_window_jitter_list` / `get_window_jitter`), which could be reduced to matching only once, e.g. by making `get_window_jitter` return `-1` and comparing to that value to determine whether it was matched or not.
2. Compared to `--not`, you have to do this on each event rather than only when the idle callback is called. That is of course significantly more expensive as events are extremely high-traffic, and you end up querying the pointer a bunch of times for each of these events.
3. In ` jitter_window_match` you're walking through your list twice (potentially), you could instead fetch both name and class and then walk through it once.
4. A very simple trick that'd probably significantly reduce overhead here is to memorize the last window you ran your check for, and if it's the same one, re-use the result. Moving the cursor generates thousand on thousands of events, but unless the window the cursor is on changes you don't need to run all of this logic again.

**Comment by Cardosaum** [comment]
Thank you so much for the feedback!

I'll try to fix it :)

**Comment by Cardosaum** [comment]
WOW haha

So few modification to such a great improvement!
[Here is the link for version comparison](https://github.com/Airblader/unclutter-xfixes/compare/master...Cardosaum:feature-window-jitter?expand=1)

In the tests I performed in my computer the CPU consumption of both branch master and feature-window-jitter are basically the same.

It's kind of simple the modifications suggested, but I didn't spot them and now that they are in place the difference is notable :)

Thank you so much for your attention and, though a _"very quick look"_, such a great improvement on the code.

**Comment by Cardosaum** [comment]
Ok, it seems there is an error I didn't handle yet. 

If we try to fetch some property of a window after it being destroyed we get a
"BadWindow" error.

Reading [this SO answer](https://stackoverflow.com/a/25352089/10719703) I think I understood what need to be done. I'll try to fix it.

**Comment by Cardosaum** [comment]
Alright, now I think it's solved. 
(at least it doesn't crash in my computer anymore haha)
