### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by Vistaus** [Airblader/unclutter-xfixes#69]
I just switched to Wayland and the one thing I miss a lot is Unclutter. It would be great if you could somehow support Wayland. :)

**Comment by Airblader** [comment]
unclutter-xfixes works based off of the Xfixes extension. This doesn't even conceptually exist in Wayland, so unfortunately this isn't something we can do, sorry.

**Comment by Vistaus** [comment]
Can't you port Xfixes to Wayland in one way or another?

**Comment by Airblader** [comment]
I don't know enough about Wayland to say whether that idea makes little or no sense. :-) I'm sure Wayland either has ways to hide the cursor or could be extended to do so, but that's really outside the scope of this project. X and Wayland would be so different that it makes more sense to just create a separate tool for Wayland.

**Comment by Vistaus** [comment]
The only Wayland alternative to unclutter that I found was an option in Sway, but I'm using KDE so that's not going to work.

Could you look into making a separate tool for Wayland? I'd really appreciate that and would even donate to make it happen. :-)

**Comment by Airblader** [comment]
I don't really know anything about Wayland and don't use it myself, so someone else will have to do that, sorry. Happy to link to any Wayland-specific replacement, though.
