### ISSUE TITLE
Doesn't always hide the cursor (touchscreen)

### ISSUE THREAD

**Issue by Scorpion2185** [Airblader/unclutter-xfixes#77]
On [Sxmo](https://sxmo.org/) the cursor is always hidden, it is meant for touchscreen devices.
It uses this app to do it (on the x version).

But it doesn't work on Debian this is the service that is used:
```
[Unit]
Description=Hides mouse pointer while not in use

[Service]
Type=simple
Restart=always
ExecStart=/usr/bin/unclutter-xfixes --hide-on-touch --start-hidden
```
It stated that those two are unrecognized options, that I don't see on the man page indeed.

**Comment by Airblader** [comment]
Debian being Debian, what version (`unclutter-xfixes --version`) do you have? Both of these features required [v1.6](https://github.com/Airblader/unclutter-xfixes/releases/tag/v1.6).

**Comment by Scorpion2185** [comment]
It is `1.5-3`.
