### ISSUE TITLE
Version in Debian Repositories is out of date

### ISSUE THREAD

**Issue by seb512** [Airblader/unclutter-xfixes#78]
Would it be possible to update the version in the official Debian repository to 1.6.1? This has already been done in the Fedora one.

Reference: https://packages.debian.org/sid/unclutter-xfixes/

**Comment by xtaran** [comment]
`unclutter-xfixes` [has been orphaned in Debian](https://bugs.debian.org/1017881) and hence currently has no maintainer — which is probably the main reason for lacking updates in Debian Unstable.

Luckily [someone intends to adopt Debian's `unclutter-xfixes` package](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1017881#12), so it hopefully should be up to date again soon.

**Comment by seb512** [comment]
Alright thanks for the update

Seb
________________________________

**Comment by Airblader** [comment]
I do not provide any packages, that's left to the distros.
