### ISSUE TITLE
Autostart via Xsession does not work under Wayland

### ISSUE THREAD

**Issue by thisisrandy** [Airblader/unclutter-xfixes#79]
I am running Ubuntu 22.04, which evidently uses Wayland rather than X. While `unclutter` still works when started manually, the autostart feature using Xsession does not. I've asked about it [here](https://askubuntu.com/q/1443862/1014459) on askubuntu. I'm sure there's some way to configure `unclutter` to autostart under Wayland, though I've yet to discover how. It would be great to have such configuration built into the `unclutter` distribution package. I'll report back if I'm able to figure it out on my own.

**Comment by pghvlaans** [comment]
It looks like that particular file actually belongs to a separate package called [unclutter-startup](https://packages.ubuntu.com/jammy/unclutter-startup) on Debian-based distributions. It might be a good idea to make a bug report to Ubuntu.

**Comment by thisisrandy** [comment]
Yes, I see that now. `unclutter-startup` seems to be installed together with `unclutter-xfixes` via `apt`, a fact which I missed. I'll move the discussion over there.
