### ISSUE TITLE
apt installs just version 1.5

### ISSUE THREAD

**Issue by AgileInteractive** [Airblader/unclutter-xfixes#80]
_apt install unclutter-xfixes_

Using Linux Mint 20.3, this just installs version 1.5-3. Manually providing version number 1.6 just reports that it does not exist.

**Comment by Airblader** [comment]
Please report this to the package maintainers. I'm only providing software, not hosting the packages.

**Comment by AgileInteractive** [comment]
How do I find out who maintains the package?

**Comment by Airblader** [comment]
I don't know how Linux Mint works, but I assume there's some forum or mailing list where you can ask how to report outdated packages.
